import FileSystem from 'fs-extra'
import Path from 'path'
import URL from 'url'

const Process = process

const FilePath = URL.fileURLToPath(import.meta.url)
const ThatPackage = FileSystem.readJsonSync('package.json', { 'encoding': 'utf-8' })

Process.exitCode = 0

try {

  console.log()
  console.log(`Generated By: ${Path.relative('', FilePath)}`)
  console.log(`Package:      ${ThatPackage.name}`)
  console.log(`Description:  ${ThatPackage.description}`)
  console.log(`Version:      ${ThatPackage.version}`)
  console.log(`License:      ${ThatPackage.license}`)
  console.log(`Author:       ${ThatPackage.author}`)
  console.log(`Repository:   ${ThatPackage.repository.url}`)
  console.log(`Source:       ${Process.env.SOURCE_PATH}`)
  console.log(`Environment:  ${Process.env.NODE_ENV}`)

} catch (error) {
  Process.exitCode = 1
  console.error(error)
}
